# Installation
Required installations:
* Python
* Jupyter/Anaconda
* necessary packages
Install Anaconda 3 only
##  For Linux Users:
#### To Install with Anaconda:
Go to http://docs.anaconda.com/anaconda/install/linux/
<br>To just install jupyter
> pip install jupyter 

##  For Windows Users:
#### To install Python
Go to https://www.python.org/downloads/windows/
Select an excutable installer for python 3.6.5
Run & Follow The instructions
#### To install with Anaconda:
Go to http://docs.anaconda.com/anaconda/install/windows/

##  For MacOs Users:
#### To install with Anaconda:
Go to http://docs.anaconda.com/anaconda/install/mac-os/


# Using Jupyter Notebook

A Jupyter notebook consists of cells<br>
To Execute a cell press `Shift+Enter` when the cell is selected.
There are two modes in a jupyter notebook `Command Mode`,`Edit Mode`,each with a certain set of operations.
In `Edit Mode` the cell is green.In `Command Mode` the cell is blue.
press `Esc` to enter `Command Mode`. press `Enter` to enter `Edit Mode`.To get a list of actions enter command mode and press `H`.<br>
Some other basic commands<br>
`A`: In Command Mode , inserts cell above<br>
`B`: In Command Mode ,inserts cell below<br>
`D,D`: In Command Mode, deletes a cell<br>
`Z`: Undo Cell deletion<br>
`?`: In Edit Mode,To get documentation help<br>
`!`: At starting of cell to run shell commands <br>
`Tab`: To get suggestions

# Python Basics

In [1]:
! python --version # check whether your version is 3.x 

Python 3.6.5 :: Anaconda, Inc.


## Foundations

In [2]:
# python does not have explicit typing. A variable can be integer at a instant String in another
a = 1
print("a is a ",type(a))
a = "HI"
print("a is now a ",type(a))

a is a  <class 'int'>
a is now a  <class 'str'>


In [3]:
# python control statements
# indentation matters!
if type(a) is int:
    print("a is an integer")
elif type(a) is str:
    print("a is a string")
else:
    print("a is something else")

a is a string


In [4]:
# python loop statements
# indentation matters!
for i in range(10):
    print("Iteration ",i+1)
i = 10
while i>0:
    print("Reverse Iteration",i)
    i -= 1 # -- does not exist in python

Iteration  1
Iteration  2
Iteration  3
Iteration  4
Iteration  5
Iteration  6
Iteration  7
Iteration  8
Iteration  9
Iteration  10
Reverse Iteration 10
Reverse Iteration 9
Reverse Iteration 8
Reverse Iteration 7
Reverse Iteration 6
Reverse Iteration 5
Reverse Iteration 4
Reverse Iteration 3
Reverse Iteration 2
Reverse Iteration 1


## Lists
Lists can store objects of any data type.

### Initialization

In [5]:
a = [1,2.0,True,"Hello",[2,3,4]] # elements can have different types
print(a)
b = range(6) # don't worry
a = list(b) # list(iterable)
print(a)
a = [x**2 for x in range(10)] # list comprehension
print(a)

[1, 2.0, True, 'Hello', [2, 3, 4]]
[0, 1, 2, 3, 4, 5]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Operations / Functions

In [6]:
a = [1,2,3]
print("Length of a is ",len(a))

Length of a is  3


In [7]:
a = [1,2,3]
print("a before appending",a)
a.append(4) # appends element to the end of list
print("a after appending",a)

a before appending [1, 2, 3]
a after appending [1, 2, 3, 4]


In [8]:
a = [1,2,3]
b = [4,5]
print("a before extending",a)
a.extend(b) # appends another list(b) at the end of list (a) . Same as a = a + b
print("a after extending",a)

a before extending [1, 2, 3]
a after extending [1, 2, 3, 4, 5]


In [9]:
a = [1,3,4]
print("a before inserting",a)
a.insert(1,2) # insert(x,y) inserts y at position x
print("a after inserting",a)

a before inserting [1, 3, 4]
a after inserting [1, 2, 3, 4]


In [10]:
a = [1,2,3,3,4]
print("a before removing",a)
a.remove(3) # removes the first occurence of an element
print("a after removing",a)

a before removing [1, 2, 3, 3, 4]
a after removing [1, 2, 3, 4]


In [11]:
a = [1,2,3,4,5]
print("a before popping",a)
a.pop() # pops the last element of the list . If given index as a parameter it
# would have removed element at that index
print("a after popping",a)

a before popping [1, 2, 3, 4, 5]
a after popping [1, 2, 3, 4]


In [12]:
a = [1,2,3,4]
print("a before clearing",a)
a.clear()
print("a after clearing",a)

a before clearing [1, 2, 3, 4]
a after clearing []


In [13]:
a = [5,6,7,8]
print("Index of element whose value is 8 is",a.index(8)) # gets the index of the element in the list

Index of element whose value is 8 is 3


In [14]:
a = [1,2,3,3,3,3,4,4]
print("Count of element 3 is ",a.count(3)) # gets the count of the element in list

Count of element 3 is  4


In [15]:
a = [1,2,3,4]
print("a is ",a)
a.reverse() # reverses the ordering of a list
print("reversed a is ",a)

a is  [1, 2, 3, 4]
reversed a is  [4, 3, 2, 1]


In [16]:
a = [4,3,8,1]
print("unsorted a is ",a)
a.sort() # sorts a list
print("sorted a is",a)

unsorted a is  [4, 3, 8, 1]
sorted a is [1, 3, 4, 8]


## Sets

Sets are unordered collection of elements.
A set does not have repetition of elements.

### Initialization

In [17]:
a = {1,2,3,3,4} # direct initialization
print("direct initialization",a)
a = [1,2,3,3,4]
print("using set() function ",set(a)) # using set() function
a = { x**2 for x in range(4)} # set comprehension
print("using set comprehension",a)

direct initialization {1, 2, 3, 4}
using set() function  {1, 2, 3, 4}
using set comprehension {0, 1, 4, 9}


### Functions/Operators

In [18]:
a = {1,2,3,4}
try:
    a[2]
except Exception as e:
    print("Error:")
    print(e)
# set does not support indexing. To index convert it into list.

Error:
'set' object does not support indexing


In [19]:
a = {1,2,3,4}
b = {3,4,5,5,6}
a.add(5) # adds element to the set
print("a after adding",a)
print("b ",b)
print("a-b ",a.difference(b)) # difference set operation
print("a union b ",a.union(b)) # union  set operation
print("a intersection b",a.intersection(b)) # intersection
print("Is {1,2} subset of a :",{1,2}.issubset(a)) # subset operation
print(" a b symmetric difference :", a.symmetric_difference(b)) # symmetric difference

a after adding {1, 2, 3, 4, 5}
b  {3, 4, 5, 6}
a-b  {1, 2}
a union b  {1, 2, 3, 4, 5, 6}
a intersection b {3, 4, 5}
Is {1,2} subset of a : True
 a b symmetric difference : {1, 2, 6}


## Dictionaries
Dictionaries are key:value pairs .Similar to hash maps

### Initialization

In [20]:
a = {"Ind":1,"Pak":2,"Ban":3} # direct initialization
print(a)
a = dict([("Ind",1),("Pak",2),("Ban",3)]) # using dict() function
print(a)
a = {i:i+1 for i in range(3)} # dictionary comprehension
print(a)

{'Ind': 1, 'Pak': 2, 'Ban': 3}
{'Ind': 1, 'Pak': 2, 'Ban': 3}
{0: 1, 1: 2, 2: 3}


### Functions/Operations

In [21]:
a = {"Ind":1,"Pak":2,"Ban":3}
print("Keys",list(a.keys())) # the keys of the dictionary
print("Values",list(a.values())) # the values of the dictionary
print("Items",list(a.items())) # dictionary as a list of pairs

Keys ['Ind', 'Pak', 'Ban']
Values [1, 2, 3]
Items [('Ind', 1), ('Pak', 2), ('Ban', 3)]


In [22]:
try:
    a = {[1,2]:2} # mutable types like list cannot be keys.
except Exception as e:
    print(e)

unhashable type: 'list'


In [23]:
print(a.get("Ind"))
print(a.get("Bangladesh"))

1
None


In [24]:
try:
    print(a['Bangladesh'])
except Exception as e:
    print(e)

'Bangladesh'


## Tuples

### Initialization

In [25]:
a = (2,3) # direct initialization
a = tuple([2,3]) # using tuple() function

In [26]:
try:
    a[0] = 1
except Exception as e:
    print(e) # tuples cannot be modified ie. are immutable

'tuple' object does not support item assignment


### Functions/Operations

In [27]:
a = (2,3)
b = ("Cats","Dogs")
print(a+b)

(2, 3, 'Cats', 'Dogs')


In [28]:
a = (2,3,3,4,1,2)
print("No of times 3 occured",a.count(3)) # Counts the occurences
print("Index of first 3",a.index(3)) # Index of the first occurence

No of times 3 occured 2
Index of first 3 1


## Strings

In [29]:
a = "they don't know that we know they know we know "
# strings are treated as character arrays

In [30]:
# String Indexing
print(a)
print(a[20:]) # after the first 20 characters
print(a[:20]) # first 20 characters
print(a[20:39]) # after first 20 characters but before 40 characters

they don't know that we know they know we know
 we know they know we know
they don't know that
 we know they know 


In [31]:
a.count("know") # gets the count of substring

4

In [32]:
print(a.isalpha()) # True if all characters are alphabetic 
print(a.isalnum()) # True if it has only numericals
print("know" in a) # checks if a substring exists

False
False
True


In [33]:
# string operations
print(a*3) # appended the same string n times
print(a + "  said Monica.") # appends new string to previous string

they don't know that we know they know we knowthey don't know that we know they know we knowthey don't know that we know they know we know
they don't know that we know they know we know  said Monica.


# Numpy Basics

In [34]:
import numpy as np

## Numpy Array Initialization

In [35]:
a = np.array([[2,3,4],[4,5,6]]) # direct initialization from lists
print(a)
a = np.arange(10) # numpy array of first 10 numbers.
print(a)
a = np.ones((3,3)) # numpy array of all ones of shape 3,3
print(a)
a = np.zeros((3,3)) # numpy array of all zeroes of shape 3,3
print(a)
a = np.eye(3) # numpy array of identiy matrix of size 3
print(a)
a = np.linspace(start=11,num=10,stop=20) # selects 'nums' points between start and stop  with equal distance
print(a)

[[2 3 4]
 [4 5 6]]
[0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


## Numpy Array Atributes

In [36]:
a = np.arange(36).reshape((6,6))
print("Shape",a.shape) # shape of the numpy array
print("Size",a.size) # size of the numpy array
print("Number Of Dimensions",a.ndim) # number of array dimensions
print("Data type of the array",a.dtype) # the data type of numpy array

Shape (6, 6)
Size 36
Number Of Dimensions 2
Data type of the array int64


In [37]:
print(a[[0,1,3],[2,4,5]]) # selects elements located at 0,2 :1,4 :3,5

[ 2 10 23]


In [38]:
a > 18

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [39]:
a[a>18] # boolean masking

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

## Numpy Array Functions

In [40]:
print("Transpose:\n",a.transpose()) # transpose of the matrix
print("Original:\n",a) # original matrix remains unchanged
print("Trace:",a.trace()) # trace of the matrix

Transpose:
 [[ 0  6 12 18 24 30]
 [ 1  7 13 19 25 31]
 [ 2  8 14 20 26 32]
 [ 3  9 15 21 27 33]
 [ 4 10 16 22 28 34]
 [ 5 11 17 23 29 35]]
Original:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Trace: 105


In [41]:
print(a.mean()) # global mean
print(a.mean(axis=1)) # row-wise mean
print(a.mean(axis=0)) # column-wise mean

17.5
[ 2.5  8.5 14.5 20.5 26.5 32.5]
[15. 16. 17. 18. 19. 20.]


In [42]:
print(a.max()) # global max
print(a.max(axis=1)) # row-wise max
print(a.max(axis=0)) # column-wise max
# similarly for minimum

35
[ 5 11 17 23 29 35]
[30 31 32 33 34 35]


In [43]:
print(a.argmin(axis=0)) # position of the smallest element column wise
print(a.argmax(axis=1)) # position of the largest element row wise

[0 0 0 0 0 0]
[5 5 5 5 5 5]


In [44]:
print(a.std()) # prints the standard deviation of the elements

10.388294694831615


In [45]:
print(a.flatten()) # flattens a multi-dimensional array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [46]:
print(a.reshape(12,3)) # reshapes the numpy array to a new shape

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]]


In [47]:
print(a-18) # subtracts all elements by the number
print()
print(a - np.arange(6)) # subtracts each row .Broadcast
# similarly addition

[[-18 -17 -16 -15 -14 -13]
 [-12 -11 -10  -9  -8  -7]
 [ -6  -5  -4  -3  -2  -1]
 [  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]]

[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]
 [24 24 24 24 24 24]
 [30 30 30 30 30 30]]


In [48]:
b = np.arange(18).reshape((6,3))
print(np.dot(a,b)) # matrix multiplication.a.dot(b) also works same

[[ 165  180  195]
 [ 435  486  537]
 [ 705  792  879]
 [ 975 1098 1221]
 [1245 1404 1563]
 [1515 1710 1905]]


In [49]:
b = np.random.randint(0,high=10,size=10) # selects random integers 
print(b)
b = np.random.normal(loc=0,scale=1,size=10) # selects randomly from a normal dirtibution
print(b)
b = np.random.choice([1,2,3,4,5],size=3,replace=False,p = [0.2]*5) # selects randomly from the given list
print(b)

[6 8 4 3 6 2 9 5 3 3]
[ 0.65631036  0.55413245  1.380326    0.57856147 -2.69634806 -1.1702464
 -0.79825789  1.05711593 -1.88246449 -0.54842019]
[3 2 5]


## [Monty Hall Problem](https://en.wikipedia.org/wiki/Monty_Hall_problem)

Suppose you’re on a game show, and you’re given the choice of three doors: Behind one door is a car; behind the others, goats. You pick a door, say No. 1, and the host, who knows what’s behind the doors, opens another door, say No. 3, which has a goat. He then says to you, “Do you want to pick door No. 2?” Is it to your advantage to switch your choice?
! ![Alt text](Monty_open_door.svg)

In [50]:
def remaining_goat(choices,taken):
    # gives the choice of the host for the given position of prize and your choice.
    goat_options = [x for x in choices if x not in taken]
    return np.random.choice(goat_options)

In [51]:
S = 1000
choices = np.array([1,2,3]) # all the choices you have
prize = np.random.choice([1,2,3],size=S) # assume prize is in one of the three doors.
your_choice = np.random.choice([1,2,3],size=S) # your choice in the S trials.
total_list = np.ones((S,3))
total_list[:,0] = prize
total_list[:,1] = your_choice
total_list[:,2] = np.array([remaining_goat(choices,total_list[i,[0,1]]) for i in range(S)]) # the host shown goat
print("Switching good %: ",np.sum(total_list[:,0] == total_list[:,1])/10)
print("Not Switching good%: ",np.sum(total_list[:,0] != total_list[:,1])/10)

Switching good %:  34.6
Not Switching good%:  65.4
